# Site settings
title: DT
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Thunder web development
baseurl: "/dt_site" # the subpath of your site, e.g. /blog/
url: "https://ryanlynch717.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
