# Site settings
title: Digital Thunder
email: info@digitalthunder.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Helping to launch your business into the digital era, Digital Thunder provide
  a wide variety of high quality services from web development to graphic design and
  advertising. Get in touch now to chat with us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://digitalthunder.co.uk" # the base hostname & protocol for your site
requireUrl: "http://digitalthunder.co.uk"
twitter_username: ryanlync
github_username: ryanlynch717

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
